max_width = 100
hard_tabs = true
tab_spaces = 2
newline_style = "Auto"
indent_style = "Block"
wrap_comments = true
comment_width = 80
format_strings = true
edition = "2015"
version = "One"
report_todo = "Never"
report_fixme = "Never"
make_backup = false
